config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :users, only:[:index, :show]
  resources :relationships, only:[:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    # Topicをパラメータの値から探し出し,Topicに紐づくcommentsとしてbuildします。
    @comment = current_user.comments.build(comments_params)
    @topic = @comment.topic
    @notification = @comment.notifications.build(user_id: @topic.user.id )
    # ↑(user_id: @topic.user.id )は(キー: 値)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: "コメントを投稿しました！" }
        # JS形式でレスポンスを返します。
        format.js { render :index }

        unless @comment.topic.user_id == current_user.id
          Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'comment_created', {
            message: 'あなたの作成したトピックにコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
        })
      else
        format.html { render :new }
      end
    end
  end

  def edit
    # @comment = Comment.find(params[:id])
    @topic = @comment.topic
  end

  def update
    # @comment = Comment.find(params[:id])
    @topic = @comment.topic
    if @comment.update(comments_params)
      redirect_to topic_path(@topic), notice: "コメントを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    # @comment = Comment.find(params[:id])
    @comment.destroy
    @topic = @comment.topic
    redirect_to topic_path(@topic), notice: "コメントを削除しました！"
  end

  private
    # ストロングパラメーター
    def comments_params
      params.require(:comment).permit(:topic_id, :content)
    end
    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <br>
  <div class="actions" style="text-align:center;">
    <%= f.submit "送信する", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<h2 class="title">編集画面</h2>
<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">

<div class="wrap">
  <% if @comment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
</div>

</div>
</div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')