config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :users, only:[:index, :show]
  resources :relationships, only:[:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  # validates :content, presence: true
  belongs_to :user
  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    # Topic.create(topics_params)
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id #form_forからuser_idは取得できないからcurrent_user.idでidを取得している（current_userはdeviseのメソッド）
    if @topic.save
      redirect_to topics_path, notice: "トピックを作成しました！"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render 'new'
    end
  end

  def edit
    # @topic = Topic.find(params[:id])
  end

  def update
    # @topic = Topic.find(params[:id])
    if @topic.update(topics_params)
      redirect_to topics_path, notice: "トピックを編集しました！"
    else
      render 'new'
    end
  end

  def show
    # showアククションを定義します。入力フォームと一覧を表示するためインスタンスを2つ生成します。
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def destroy
    # @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました！"
  end

  def confirm
    @topic = Topic.new(topics_params)
    render :new if @topic.invalid?
  end

  private
    def topics_params
      params.require(:topic).permit(:title, :content)
    end
    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_form.html.erb
<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">

<div class="wrap">
<%= form_for(@topic, url: choose_new_or_edit) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <p class="alert alert-danger"><%= @topic.errors.count %>件のエラーがあります！</p>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit "確認画面へ", class: 'btn btn-primary' %>
<% end %>
<div style="margin-top: 20px;">
  <%= link_to "トピック一覧へ", topics_path %>
</div>
</div>

</div>
</div>
</div>

app/views/topics/confirm.html.erb
<h1 class="title">確認画面</h1>
<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">

<div class="wrap">
<%= form_for(@topic) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <ul>
    <li>タイトル：<%= @topic.title %></li>
    <li>内容：<%= @topic.content %></li>
  </ul>
  <%= f.submit "投稿する", class: 'btn btn-primary' %>
<% end %>

<%= form_for(@topic, url: new_topic_path, method: 'get',) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <div style="margin-top: 10px;">
    <%= f.submit "もどる", name: 'back' %>
  </div>
<% end %>
</div>

</div>
</div>
</div>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/edit.html.erb
<h1 class="title">トピックを編集する</h1>

<%= render 'form' %>

app/views/topics/index.html.erb
<h1 class="title">トピック一覧</h1>
<p style="text-align: center; margin-top: 20px;"><%= notice %></p>

<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">

<% @topics.each do |topic| %>
<div class="wrap panel panel-default">
  <div class="panel-body">
    <ul>
      <li>タイトル：<%= link_to topic.title, topic_path(topic.id) %></li>
      <li>内容：<%= topic.content %></li>
      <li><%= profile_img(topic.user) if topic.user %></li>
      <li>投稿者：<%= topic.user.name if topic.user %></li>
    </ul>
    <% if topic.user_id == current_user.id %>
      <div style="text-align: center;">
        <%= link_to "トピックを編集する", edit_topic_path(topic.id) %>
        <%= link_to "トピックを削除する", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
      </div>
    <% end %>
  </div>
</div>
<% end %>
<p><%= link_to "トピックを作成する", new_topic_path %></p>

</div>
</div>
</div>

app/views/topics/new.html.erb
<h1 class="title">トピックを作成する</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<h1 class="title">トピック詳細</h1>
<p style="text-align: center; margin-top: 20px;"><%= notice %></p>

<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">

<div class="wrap">
  <ul>
    <li>タイトル:<%= @topic.title %></li>
    <li>本文:<%= @topic.content %></li>
    <li><%= profile_img(@topic.user) %></li>
    <li style="margin-bottom: 20px;">投稿者:<%= @topic.user.name %></li>
    <% if @topic.user_id == current_user.id %>
      <p><%= link_to "トピックを編集する", edit_topic_path %></p>
      <p><%= link_to "トピックを削除する", topic_path, method: :delete, data: { confirm: '本当に削除していいですか？' } %></p>
    <% end %>
  </ul>
  <p><%= link_to "トピックを作成する", new_topic_path %></p>
  <p><%= link_to "一覧へ戻る", topics_path %></p>
</div>
<div class="wrap">
  <h2 class="subhead">コメント一覧</h2>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
  <br>
  <% if current_user.id == @topic.user_id %>
    <%= link_to '編集', edit_topic_path(@topic) %> |
  <% end %>
  <%= link_to '戻る', topics_path %>
</div>

</div>
</div>
</div>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>