config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :users, only:[:index, :show]
  resources :relationships, only:[:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>fbook</title>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <% if user_signed_in? %>
      <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
          encrypted: true,
          cluster: 'ap1'
        });

        var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
        channel.bind('comment_created', function(data) {
          alert(data.message);
        });
        channel.bind('notification_created', function(data) {
        $('#unread_count').html(data.unread_counts);
      });
      </script>
    <% end %>
  </head>

<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "fbook", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'ユーザ一覧', users_path %></li>
              <li><%= link_to "メッセージ", conversations_path %></li>
              <li><%= link_to '投稿する', new_topic_path %></li>
              <li><%= link_to 'トピック一覧へ', topics_path %></li>
              <li><%= link_to 'マイページ', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <li>
                <%= link_to notifications_index_path, class: "navbar-brand" do %>
                  <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
  </nav>
  <%= yield %>
</body>
</html>